### ISSUE TITLE
Defaults values

### ISSUE THREAD

**Issue by oassuncao** [apigee/apigeecli#29]
I'm trying to disable a targetservers, but the parameter is not sent to Google API because we are using `omitempty`

This problem could happen with many other types (int, boolean, string, etc)
```
	IsEnabled   bool     `json:"isEnabled,omitempty"`
```

https://github.com/apigee/apigeecli/blob/a205b5f61af61a1ac433bba7f9a7fba1c8f7bdb7/client/targetservers/targetservers.go#L34

**Comment by srinandan** [comment]
I have created a fix for this issue and can create a preview release with the fix.

**Comment by oassuncao** [comment]
I guess the fix will not work properly, the JSON struct continues with omitempty. I guess this problem is occurring in other endpoints

I can test the preview release

**Comment by srinandan** [comment]
I don't think the `omitempty` in the struct matters. The method is called from [here](https://github.com/apigee/apigeecli/blob/master/cmd/targetservers/crtts.go#L52). The default value is `true`. Therefore a value is always passed (`nil` is never sent). 

Secondly, for the API itself, not sending enabled is the same as `true`. See [here](https://cloud.google.com/apigee/docs/reference/apis/apigee/rest/v1/organizations.environments.targetservers#resource:-targetserver) for reference.

The bug was that I was only sending something when `true` and nothing when `false`, therefore you couldn't disable it. But now I always send true/false, so you should be able to control it.

**Comment by srinandan** [comment]
Please try this [version](https://github.com/apigee/apigeecli/releases/tag/v1.110-beta.1) - v1.110-beta.1

**Comment by oassuncao** [comment]
I tested the new version, but the problem continues

**Comment by srinandan** [comment]
My apologies, you are correct. That did not fix the problem. I have fixed the problem in the new version and also looked at other places that may require this change (and no other struct was affected). 

Here is the new [release](https://github.com/apigee/apigeecli/releases/tag/v1.110-beta.2). Thank you for you patience and tests.

**Comment by oassuncao** [comment]
Now, it's working properly

Do you know when will release the stable and latest version?

**Comment by srinandan** [comment]
I have a release once a month. The next release is around the 25rd of July.
