### ISSUE TITLE
Add option in ApigeeCLI to use RateLimit policy

### ISSUE THREAD

**Issue by wrfleming** [apigee/apigeecli#423]
Description: Today the ability to extent the OpenAPI spec to include the RateLimit policy is there yet we would like to have the option to add it via the command line.  

For example.   apigeecli apis create -  --add-ratelimit

**Comment by ssvaidyanathan** [comment]
@wrfleming - can you elaborate more on this please? As you mentioned, apigeecli has a feature to add [rate limit policies](https://github.com/apigee/apigeecli?tab=readme-ov-file#traffic-management) as part of proxy generation when you include the custom extensions. Can you not use that?

**Comment by srinandan** [comment]
To add on top of what @ssvaidyanathan says, you can define a spec purely for the purposes of generating the proxy like this: 

```yaml
openapi: 3.0.2
info:
  version: 0.0.1
  title: Minimal Spec
servers:
  - url: https://my.example.com/api
x-google-ratelimit:
  - name: test1_test
    rate-literal: 10ps
```

You can also add API Key, OAuth and other supported policies instead of rate limit.

Then generate the API Proxy like this:
`apigeecli apis create openapi --oas-base-folderpath=$FOLDER --oas-name=$SPEC_NAME --name=$NAME --skip-policy=true --default-token` (this command assumes you have set org and other details as preferences)

**Comment by wrfleming** [comment]
Sai we would like to enforce a rate limit policy yet cannot guarantee the consumers bringing their OpenAPI spec to our developer portal will add that snippet of code. One option is that we could insert the x-google-ratelimit into the OpenAPI spec once its submitted  via the portal.

**Comment by ssvaidyanathan** [comment]
@wrfleming - Yes, can you try including that custom extension in the spec (using some script) and then generate the proxy?

I am afraid, if we open for one policy for you, we will get so many similar requests for all kind of policies and configurations.

**Comment by ssvaidyanathan** [comment]
Closing this issue as discussed
